### ISSUE TITLE
Netlify hosting?

### ISSUE THREAD

**Issue by jasonday** [sparanoid/almace-scaffolding#118]
See build log here:
https://app.netlify.com/sites/hardcore-torvalds-cb2384/deploys/5c2bd9d8b5ee113a9a3a5775

Although GitHub Pages has the issues you outlined at here:
https://sparanoid.com/lab/amsf/github-pages-setup.html

But I'm wondering if it's possible to host using Netlify?

**Comment by sparanoid** [comment]
@jasonday I hadn't used Netlify but just tired it with the latest AMSF seems everything is working. Here's the log:

https://app.netlify.com/sites/amsf-demo/deploys/5c5c10f435ffa8a37635a7c5

Demo (page URLs only work for GitHub Pages because of https://github.com/sparanoid/almace-scaffolding/issues/119):

https://amsf-demo.netlify.com/

However you have to explicitly specify the Bundler version in `Gemfile.lock` at the moment, ref https://github.com/netlify/build-image/issues/250#issuecomment-458836858

**Comment by sparanoid** [comment]
Closing for now, feel free to reopen this issue if you still have further questions regarding this.
